/*
 * File: app/store/NewsList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ElComercio.store.NewsList', {
    extend: 'Ext.data.Store',

    requires: [
        'ElComercio.model.New'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'ElComercio.model.New',
            storeId: 'NewsList',
            proxy: {
                type: 'ajax',
                url: 'app/data/temasdeldia.json',
                reader: {
                    type: 'json',
                    idProperty: 'tag',
                    root: 'news'
                }
            }
        }, cfg)]);
    }
});