/*
 * File: app/store/SearchNews.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ElComercio.store.SearchNews', {
    extend: 'Ext.data.Store',

    requires: [
        'ElComercio.model.SearchNew'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'ElComercio.model.SearchNew',
            storeId: 'SearchNews',
            pageSize: 10,
            proxy: {
                type: 'jsonp',
                url: 'http://www.sencha.com/forum/topics-remote.php',
                reader: {
                    type: 'json',
                    root: 'topics',
                    totalProperty: 'totalCount'
                }
            }
        }, cfg)]);
    }
});