/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ElComercio.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    collapseMode: 'header',
                    region: 'north',
                    height: 131,
                    items: [
                        {
                            xtype: 'image',
                            height: 88,
                            width: 418,
                            src: 'resources/images/logoec.jpg'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'north',
                    height: 128
                },
                {
                    xtype: 'container',
                    region: 'east',
                    width: 229
                },
                {
                    xtype: 'container',
                    region: 'west',
                    width: 440
                },
                {
                    xtype: 'container',
                    region: 'south',
                    height: 168
                }
            ]
        });

        me.callParent(arguments);
    }

});