/*
 * File: app/view/VwpMain.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ElComercio.view.VwpMain', {
    extend: 'Ext.container.Viewport',

    cls: 'vwpmain',
    itemId: 'VwpMain',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    cls: 'cont_1',
                    id: 'cnt_1',
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'container',
                            cls: 'cont_header',
                            frame: false,
                            id: 'cntHeader',
                            layout: {
                                type: 'table'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'cont_logo',
                                    id: 'cntLogo',
                                    items: [
                                        {
                                            xtype: 'image',
                                            id: 'imgLogo',
                                            src: 'img/logo_elComercio.jpg'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    cls: 'cont_options',
                                    id: 'cntOptions',
                                    layout: {
                                        type: 'absolute'
                                    },
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            id: 'cmbSearchNews',
                                            width: 300,
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            hideTrigger: true,
                                            displayField: 'title',
                                            store: 'SearchNews'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    cls: 'cont_2',
                    id: 'cnt_2',
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'container',
                            cls: 'cont_body',
                            id: 'cntBody',
                            layout: {
                                type: 'absolute'
                            },
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'cnt_viewtop',
                                    id: 'cntViewTop',
                                    layout: {
                                        type: 'absolute'
                                    },
                                    items: [
                                        {
                                            xtype: 'dataview',
                                            cls: 'lvw_top',
                                            id: 'lvwTop',
                                            itemSelector: 'div.thumb-wrap',
                                            itemTpl: [
                                                '<tpl for=".">',
                                                '    <div class="thumb-wrap" id="top_{id}">',
                                                '        <a href="{link}" title="img-{id}">',
                                                '            <img src="{img}" title="img-{id}">',
                                                '        </a>',
                                                '        <div class="lostextos">',
                                                '            <p class="ptxt">',
                                                '                <a class="ltxt" href="{link}" >',
                                                '                    {title}',
                                                '                </a>',
                                                '            </p>',
                                                '        </div>',
                                                '    </div>',
                                                '</tpl>'
                                            ],
                                            store: 'NewsList'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    y: 310,
                                    cls: 'cnt_center',
                                    id: 'cntCenter',
                                    layout: {
                                        type: 'column'
                                    },
                                    items: [
                                        {
                                            xtype: 'container',
                                            split: 'true',
                                            collapsible: 'true',
                                            cls: 'cnt_viewleft',
                                            id: 'cntViewLeft',
                                            layout: {
                                                type: 'border'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    region: 'north',
                                                    id: 'cntViewTop1'
                                                },
                                                {
                                                    xtype: 'container',
                                                    region: 'west',
                                                    id: 'cntViewLeft1'
                                                },
                                                {
                                                    xtype: 'container',
                                                    region: 'east',
                                                    id: 'cntViewRight1'
                                                },
                                                {
                                                    xtype: 'label',
                                                    region: 'center',
                                                    text: 'My Label'
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            cls: 'cnt_viewright',
                                            id: 'cntViewRight',
                                            items: [
                                                {
                                                    xtype: 'label',
                                                    text: 'My Labeldssd sfdsf sd  sfsdf wferwd weg'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});